# These are supported funding model platforms

github: https://github.com/CrAcKy-glitch
patreon: https://patreon.com
open_collective: # Replace with a single Open Collective username
buy_me_a_coffee:
custom: https://intelansh.onrender.com
